/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.okil.voxelizedfurniture.init;

import net.okil.voxelizedfurniture.item.JamBottleItem;
import net.okil.voxelizedfurniture.VoxelizedFurnitureMod;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.Identifier;
import net.minecraft.core.registries.Registries;

import java.util.function.Function;

public class VoxelizedFurnitureModItems {
	public static Item CABINET_OAK;
	public static Item CABINET_BIRCH;
	public static Item CABINET_DARK_OAK;
	public static Item CABINET_ACACIA;
	public static Item CABINET_MANGROVE;
	public static Item CABINET_CHERRY;
	public static Item CABINET_JUNGLE;
	public static Item CABINET_BAMBOO;
	public static Item FRIDGE;
	public static Item OAK_SINK;
	public static Item SPRUCE_SINK;
	public static Item MANGROVE_SINK;
	public static Item JUNGLE_SINK;
	public static Item DARK_OAK_SINK;
	public static Item BIRCH_SINK;
	public static Item ACACIA_SINK;
	public static Item CHERRY_SINK;
	public static Item BAMBOO_SINK;
	public static Item CABINET_SPRUCE;
	public static Item JAM_JAR;
	public static Item HONEY_JAR;
	public static Item JAM_BOTTLE;
	public static Item SHOWER;
	public static Item OAK_SHELF;
	public static Item SPRUCE_SHELF;
	public static Item MANGROVE_SHELF;
	public static Item JUNGLE_SHELF;
	public static Item DARK_OAK_SHELF;
	public static Item CHERRY_SHELF;
	public static Item BIRCH_SHELF;
	public static Item BAMBOO_SHELF;
	public static Item ACACIA_SHELF;
	public static Item SOAP;
	public static Item OAK_CHAIR_1;
	public static Item SPRUCE_CHAIR_1;
	public static Item MANGROVE_CHAIR_1;
	public static Item JUNGLE_CHAIR_1;
	public static Item DARK_OAK_CHAIR_1;
	public static Item CHERRY_CHAIR_1;
	public static Item BIRCH_CHAIR_1;
	public static Item BAMBOO_CHAIR_1;
	public static Item ACACIA_CHAIR_1;
	public static Item GROUND_DEV_TEX;
	public static Item GOLDEN_DESKTOP_FOUNTAIN;
	public static Item POTTED_GREEN_PLANT;
	public static Item GOLDEN_ZEN_FOUNTAIN;
	public static Item TV;
	public static Item LAPTOP;
	public static Item ASPHALT;
	public static Item DOUBLE_BED;
	public static Item SINGLE_BED;
	public static Item OAK_WARDROBE;
	public static Item SPRUCE_WARDROBE;
	public static Item MANGROVE_WARDROBE;
	public static Item JUNGLE_WARDROBE;
	public static Item DARK_OAK_WARDROBE;
	public static Item CHERRY_WARDROBE;
	public static Item BIRCH_WARDROBE;
	public static Item BAMBOO_WARDROBE;
	public static Item ACACIA_WARDROBE;
	public static Item LIGHT;
	public static Item LIGHT_SWITCH_BUTTON;
	public static Item KITCHEN_DRAWER;
	public static Item KITCHEN_DRAWER_1;
	public static Item KITCHEN_SINK;
	public static Item OVEN;
	public static Item OVEN_VENT;
	public static Item KITCHEN_TABLE;
	public static Item KITCHEN_DRAWER_CORNER;
	public static Item KITCHEN_FRIDGE;
	public static Item MODERN_BULKHEAD_LIGHT_OFF;
	public static Item OAK_COBBLE_PATH;
	public static Item SPRUCE_COBBLE_PATH;
	public static Item MANGROVE_COBBLE_PATH;
	public static Item JUNGLE_COBBLE_PATH;
	public static Item DARK_OAK_COBBLE_PATH;
	public static Item CHERRY_COBBLE_PATH;
	public static Item BIRCH_COBBLE_PATH;
	public static Item BAMBOO_COBBLE_PATH;
	public static Item ACACIA_COBBLE_PATH;
	public static Item OAK_DOORBELL;
	public static Item SPRUCE_DOORBELL;
	public static Item MANGROVE_DOORBELL;
	public static Item JUNGLE_DOORBELL;
	public static Item DARK_OAK_DOORBELL;
	public static Item CHERRY_DOORBELL;
	public static Item BIRCH_DOORBELL;
	public static Item BAMBOO_DOORBELL;
	public static Item ACACIA_DOORBELL;
	public static Item OAK_PORCH_TABLE;
	public static Item SPRUCE_PORCH_TABLE;
	public static Item MANGROVE_PORCH_TABLE;
	public static Item JUNGLE_PORCH_TABLE;
	public static Item DARK_OAK_PORCH_TABLE;
	public static Item CHERRY_PORCH_TABLE;
	public static Item BIRCH_PORCH_TABLE;
	public static Item BAMBOO_PORCH_TABLE;
	public static Item ACACIA_PORCH_TABLE;
	public static Item AMETHYST_GEODE;
	public static Item EMERALD_GEODE;
	public static Item DIAMOND_GEODE;
	public static Item REDSTONE_GEODE;
	public static Item MINIATURE_RUINED_NETHER_PORTAL;
	public static Item MINIATURE_WATER_RUIN;
	public static Item OAK_TOILET_ROLL;
	public static Item SPRUCE_TOILET_ROLL;
	public static Item MANGROVE_TOILET_ROLL;
	public static Item JUNGLE_TOILET_ROLL;
	public static Item DARK_OAK_TOILET_ROLL;
	public static Item CHERRY_TOILET_ROLL;
	public static Item BIRCH_TOILET_ROLL;
	public static Item BAMBOO_TOILET_ROLL;
	public static Item ACACIA_TOILET_ROLL;
	public static Item GREEN_BAMBOO_PLANT;
	public static Item BARREL_PLANT;
	public static Item SEED_IN_POT;
	public static Item SEED_IN_POT_RAMDOM;
	public static Item CUBE_CEILING_LIGHT;
	public static Item YUCCA_PLANT;
	public static Item YUCCA_PLANT_RANDOM;
	public static Item WHEAT_PLANT;
	public static Item RANDOM_WHEAT_PLANT;
	public static Item BRICKS;
	public static Item CACTUS_PLANT;
	public static Item CACTUS_PLANT_RANDOM;
	public static Item OAK_DRAWER;
	public static Item SPRUCE_DRAWER;
	public static Item JUNGLE_DRAWER;
	public static Item DARK_OAK_DRAWER;
	public static Item CHERRY_DRAWER;
	public static Item BIRCH_DRAWER;
	public static Item BAMBOO_DRAWER;
	public static Item ACACIA_DRAWER;
	public static Item MANGROVE_DRAWER;
	public static Item KYANITE;
	public static Item BAMBOO_CLUSTER;
	public static Item PAN;
	public static Item AIRFRYER;
	public static Item MICROWAVE;
	public static Item TOASTER_WHITE;
	public static Item TOASTER_BLUE;
	public static Item TOASTER_BROWN;
	public static Item TOASTER_CYAN;
	public static Item TOASTER_GRAY;
	public static Item TOASTER_GREEN;
	public static Item TOASTER_LIGHT_BLUE;
	public static Item TOASTER_LIGHT_GRAY;
	public static Item TOASTER_LIME;
	public static Item TOASTER_MAGENTA;
	public static Item TOASTER_ORANGE;
	public static Item TOASTER_PINK;
	public static Item TOASTER_PURPLE;
	public static Item TOASTER_RED;
	public static Item TOASTER_YELLOW;
	public static Item WOODEN_CRATE;
	public static Item SACK_OF_SOIL;
	public static Item GRAY_WATERING_CAN;
	public static Item BLUE_WATERING_CAN;
	public static Item GREEN_WATERING_CAN;
	public static Item WOODEN_KITCHEN_DRAWER;
	public static Item WOODEN_OVEN_COOKTOP;
	public static Item WOODEN_KITCHEN_SINK;
	public static Item SOFT_OAK;
	public static Item SOFT_PALE_OAK;
	public static Item SOFT_DARK_OAK;
	public static Item WOODEN_KITCHEN_EXHAUSTHOOD;
	public static Item WOODEN_KITCHEN_CABINET_ABOVE;

	public static void load() {
		CABINET_OAK = block(VoxelizedFurnitureModBlocks.CABINET_OAK, "cabinet_oak");
		CABINET_BIRCH = block(VoxelizedFurnitureModBlocks.CABINET_BIRCH, "cabinet_birch");
		CABINET_DARK_OAK = block(VoxelizedFurnitureModBlocks.CABINET_DARK_OAK, "cabinet_dark_oak");
		CABINET_ACACIA = block(VoxelizedFurnitureModBlocks.CABINET_ACACIA, "cabinet_acacia");
		CABINET_MANGROVE = block(VoxelizedFurnitureModBlocks.CABINET_MANGROVE, "cabinet_mangrove");
		CABINET_CHERRY = block(VoxelizedFurnitureModBlocks.CABINET_CHERRY, "cabinet_cherry");
		CABINET_JUNGLE = block(VoxelizedFurnitureModBlocks.CABINET_JUNGLE, "cabinet_jungle");
		CABINET_BAMBOO = block(VoxelizedFurnitureModBlocks.CABINET_BAMBOO, "cabinet_bamboo");
		FRIDGE = block(VoxelizedFurnitureModBlocks.FRIDGE, "fridge", new Item.Properties().fireResistant());
		OAK_SINK = block(VoxelizedFurnitureModBlocks.OAK_SINK, "oak_sink");
		SPRUCE_SINK = block(VoxelizedFurnitureModBlocks.SPRUCE_SINK, "spruce_sink");
		MANGROVE_SINK = block(VoxelizedFurnitureModBlocks.MANGROVE_SINK, "mangrove_sink");
		JUNGLE_SINK = block(VoxelizedFurnitureModBlocks.JUNGLE_SINK, "jungle_sink");
		DARK_OAK_SINK = block(VoxelizedFurnitureModBlocks.DARK_OAK_SINK, "dark_oak_sink");
		BIRCH_SINK = block(VoxelizedFurnitureModBlocks.BIRCH_SINK, "birch_sink");
		ACACIA_SINK = block(VoxelizedFurnitureModBlocks.ACACIA_SINK, "acacia_sink");
		CHERRY_SINK = block(VoxelizedFurnitureModBlocks.CHERRY_SINK, "cherry_sink");
		BAMBOO_SINK = block(VoxelizedFurnitureModBlocks.BAMBOO_SINK, "bamboo_sink");
		CABINET_SPRUCE = block(VoxelizedFurnitureModBlocks.CABINET_SPRUCE, "cabinet_spruce");
		JAM_JAR = block(VoxelizedFurnitureModBlocks.JAM_JAR, "jam_jar");
		HONEY_JAR = block(VoxelizedFurnitureModBlocks.HONEY_JAR, "honey_jar");
		JAM_BOTTLE = register("jam_bottle", JamBottleItem::new);
		SHOWER = block(VoxelizedFurnitureModBlocks.SHOWER, "shower", new Item.Properties().fireResistant());
		OAK_SHELF = block(VoxelizedFurnitureModBlocks.OAK_SHELF, "oak_shelf");
		SPRUCE_SHELF = block(VoxelizedFurnitureModBlocks.SPRUCE_SHELF, "spruce_shelf");
		MANGROVE_SHELF = block(VoxelizedFurnitureModBlocks.MANGROVE_SHELF, "mangrove_shelf");
		JUNGLE_SHELF = block(VoxelizedFurnitureModBlocks.JUNGLE_SHELF, "jungle_shelf");
		DARK_OAK_SHELF = block(VoxelizedFurnitureModBlocks.DARK_OAK_SHELF, "dark_oak_shelf");
		CHERRY_SHELF = block(VoxelizedFurnitureModBlocks.CHERRY_SHELF, "cherry_shelf");
		BIRCH_SHELF = block(VoxelizedFurnitureModBlocks.BIRCH_SHELF, "birch_shelf");
		BAMBOO_SHELF = block(VoxelizedFurnitureModBlocks.BAMBOO_SHELF, "bamboo_shelf");
		ACACIA_SHELF = block(VoxelizedFurnitureModBlocks.ACACIA_SHELF, "acacia_shelf");
		SOAP = block(VoxelizedFurnitureModBlocks.SOAP, "soap", new Item.Properties().fireResistant());
		OAK_CHAIR_1 = block(VoxelizedFurnitureModBlocks.OAK_CHAIR_1, "oak_chair_1");
		SPRUCE_CHAIR_1 = block(VoxelizedFurnitureModBlocks.SPRUCE_CHAIR_1, "spruce_chair_1");
		MANGROVE_CHAIR_1 = block(VoxelizedFurnitureModBlocks.MANGROVE_CHAIR_1, "mangrove_chair_1");
		JUNGLE_CHAIR_1 = block(VoxelizedFurnitureModBlocks.JUNGLE_CHAIR_1, "jungle_chair_1");
		DARK_OAK_CHAIR_1 = block(VoxelizedFurnitureModBlocks.DARK_OAK_CHAIR_1, "dark_oak_chair_1");
		CHERRY_CHAIR_1 = block(VoxelizedFurnitureModBlocks.CHERRY_CHAIR_1, "cherry_chair_1");
		BIRCH_CHAIR_1 = block(VoxelizedFurnitureModBlocks.BIRCH_CHAIR_1, "birch_chair_1");
		BAMBOO_CHAIR_1 = block(VoxelizedFurnitureModBlocks.BAMBOO_CHAIR_1, "bamboo_chair_1");
		ACACIA_CHAIR_1 = block(VoxelizedFurnitureModBlocks.ACACIA_CHAIR_1, "acacia_chair_1");
		GROUND_DEV_TEX = block(VoxelizedFurnitureModBlocks.GROUND_DEV_TEX, "ground_dev_tex", new Item.Properties().fireResistant());
		GOLDEN_DESKTOP_FOUNTAIN = block(VoxelizedFurnitureModBlocks.GOLDEN_DESKTOP_FOUNTAIN, "golden_desktop_fountain");
		POTTED_GREEN_PLANT = block(VoxelizedFurnitureModBlocks.POTTED_GREEN_PLANT, "potted_green_plant", new Item.Properties().fireResistant());
		GOLDEN_ZEN_FOUNTAIN = block(VoxelizedFurnitureModBlocks.GOLDEN_ZEN_FOUNTAIN, "golden_zen_fountain");
		TV = block(VoxelizedFurnitureModBlocks.TV, "tv", new Item.Properties().rarity(Rarity.RARE).fireResistant());
		LAPTOP = block(VoxelizedFurnitureModBlocks.LAPTOP, "laptop", new Item.Properties().rarity(Rarity.RARE).fireResistant());
		ASPHALT = block(VoxelizedFurnitureModBlocks.ASPHALT, "asphalt", new Item.Properties().fireResistant());
		DOUBLE_BED = block(VoxelizedFurnitureModBlocks.DOUBLE_BED, "double_bed");
		SINGLE_BED = block(VoxelizedFurnitureModBlocks.SINGLE_BED, "single_bed");
		OAK_WARDROBE = block(VoxelizedFurnitureModBlocks.OAK_WARDROBE, "oak_wardrobe");
		SPRUCE_WARDROBE = block(VoxelizedFurnitureModBlocks.SPRUCE_WARDROBE, "spruce_wardrobe");
		MANGROVE_WARDROBE = block(VoxelizedFurnitureModBlocks.MANGROVE_WARDROBE, "mangrove_wardrobe");
		JUNGLE_WARDROBE = block(VoxelizedFurnitureModBlocks.JUNGLE_WARDROBE, "jungle_wardrobe");
		DARK_OAK_WARDROBE = block(VoxelizedFurnitureModBlocks.DARK_OAK_WARDROBE, "dark_oak_wardrobe");
		CHERRY_WARDROBE = block(VoxelizedFurnitureModBlocks.CHERRY_WARDROBE, "cherry_wardrobe");
		BIRCH_WARDROBE = block(VoxelizedFurnitureModBlocks.BIRCH_WARDROBE, "birch_wardrobe");
		BAMBOO_WARDROBE = block(VoxelizedFurnitureModBlocks.BAMBOO_WARDROBE, "bamboo_wardrobe");
		ACACIA_WARDROBE = block(VoxelizedFurnitureModBlocks.ACACIA_WARDROBE, "acacia_wardrobe");
		LIGHT = block(VoxelizedFurnitureModBlocks.LIGHT, "light", new Item.Properties().fireResistant());
		LIGHT_SWITCH_BUTTON = block(VoxelizedFurnitureModBlocks.LIGHT_SWITCH_BUTTON, "light_switch_button", new Item.Properties().fireResistant());
		KITCHEN_DRAWER = block(VoxelizedFurnitureModBlocks.KITCHEN_DRAWER, "kitchen_drawer", new Item.Properties().fireResistant());
		KITCHEN_DRAWER_1 = block(VoxelizedFurnitureModBlocks.KITCHEN_DRAWER_1, "kitchen_drawer_1", new Item.Properties().fireResistant());
		KITCHEN_SINK = block(VoxelizedFurnitureModBlocks.KITCHEN_SINK, "kitchen_sink", new Item.Properties().fireResistant());
		OVEN = block(VoxelizedFurnitureModBlocks.OVEN, "oven", new Item.Properties().fireResistant());
		OVEN_VENT = block(VoxelizedFurnitureModBlocks.OVEN_VENT, "oven_vent");
		KITCHEN_TABLE = block(VoxelizedFurnitureModBlocks.KITCHEN_TABLE, "kitchen_table", new Item.Properties().fireResistant());
		KITCHEN_DRAWER_CORNER = block(VoxelizedFurnitureModBlocks.KITCHEN_DRAWER_CORNER, "kitchen_drawer_corner", new Item.Properties().fireResistant());
		KITCHEN_FRIDGE = block(VoxelizedFurnitureModBlocks.KITCHEN_FRIDGE, "kitchen_fridge", new Item.Properties().fireResistant());
		MODERN_BULKHEAD_LIGHT_OFF = block(VoxelizedFurnitureModBlocks.MODERN_BULKHEAD_LIGHT_OFF, "modern_bulkhead_light_off", new Item.Properties().fireResistant());
		OAK_COBBLE_PATH = block(VoxelizedFurnitureModBlocks.OAK_COBBLE_PATH, "oak_cobble_path", new Item.Properties().fireResistant());
		SPRUCE_COBBLE_PATH = block(VoxelizedFurnitureModBlocks.SPRUCE_COBBLE_PATH, "spruce_cobble_path", new Item.Properties().fireResistant());
		MANGROVE_COBBLE_PATH = block(VoxelizedFurnitureModBlocks.MANGROVE_COBBLE_PATH, "mangrove_cobble_path", new Item.Properties().fireResistant());
		JUNGLE_COBBLE_PATH = block(VoxelizedFurnitureModBlocks.JUNGLE_COBBLE_PATH, "jungle_cobble_path", new Item.Properties().fireResistant());
		DARK_OAK_COBBLE_PATH = block(VoxelizedFurnitureModBlocks.DARK_OAK_COBBLE_PATH, "dark_oak_cobble_path", new Item.Properties().fireResistant());
		CHERRY_COBBLE_PATH = block(VoxelizedFurnitureModBlocks.CHERRY_COBBLE_PATH, "cherry_cobble_path", new Item.Properties().fireResistant());
		BIRCH_COBBLE_PATH = block(VoxelizedFurnitureModBlocks.BIRCH_COBBLE_PATH, "birch_cobble_path", new Item.Properties().fireResistant());
		BAMBOO_COBBLE_PATH = block(VoxelizedFurnitureModBlocks.BAMBOO_COBBLE_PATH, "bamboo_cobble_path", new Item.Properties().fireResistant());
		ACACIA_COBBLE_PATH = block(VoxelizedFurnitureModBlocks.ACACIA_COBBLE_PATH, "acacia_cobble_path", new Item.Properties().fireResistant());
		OAK_DOORBELL = block(VoxelizedFurnitureModBlocks.OAK_DOORBELL, "oak_doorbell");
		SPRUCE_DOORBELL = block(VoxelizedFurnitureModBlocks.SPRUCE_DOORBELL, "spruce_doorbell");
		MANGROVE_DOORBELL = block(VoxelizedFurnitureModBlocks.MANGROVE_DOORBELL, "mangrove_doorbell");
		JUNGLE_DOORBELL = block(VoxelizedFurnitureModBlocks.JUNGLE_DOORBELL, "jungle_doorbell");
		DARK_OAK_DOORBELL = block(VoxelizedFurnitureModBlocks.DARK_OAK_DOORBELL, "dark_oak_doorbell");
		CHERRY_DOORBELL = block(VoxelizedFurnitureModBlocks.CHERRY_DOORBELL, "cherry_doorbell");
		BIRCH_DOORBELL = block(VoxelizedFurnitureModBlocks.BIRCH_DOORBELL, "birch_doorbell");
		BAMBOO_DOORBELL = block(VoxelizedFurnitureModBlocks.BAMBOO_DOORBELL, "bamboo_doorbell");
		ACACIA_DOORBELL = block(VoxelizedFurnitureModBlocks.ACACIA_DOORBELL, "acacia_doorbell");
		OAK_PORCH_TABLE = block(VoxelizedFurnitureModBlocks.OAK_PORCH_TABLE, "oak_porch_table", new Item.Properties().fireResistant());
		SPRUCE_PORCH_TABLE = block(VoxelizedFurnitureModBlocks.SPRUCE_PORCH_TABLE, "spruce_porch_table", new Item.Properties().fireResistant());
		MANGROVE_PORCH_TABLE = block(VoxelizedFurnitureModBlocks.MANGROVE_PORCH_TABLE, "mangrove_porch_table", new Item.Properties().fireResistant());
		JUNGLE_PORCH_TABLE = block(VoxelizedFurnitureModBlocks.JUNGLE_PORCH_TABLE, "jungle_porch_table", new Item.Properties().fireResistant());
		DARK_OAK_PORCH_TABLE = block(VoxelizedFurnitureModBlocks.DARK_OAK_PORCH_TABLE, "dark_oak_porch_table", new Item.Properties().fireResistant());
		CHERRY_PORCH_TABLE = block(VoxelizedFurnitureModBlocks.CHERRY_PORCH_TABLE, "cherry_porch_table", new Item.Properties().fireResistant());
		BIRCH_PORCH_TABLE = block(VoxelizedFurnitureModBlocks.BIRCH_PORCH_TABLE, "birch_porch_table", new Item.Properties().fireResistant());
		BAMBOO_PORCH_TABLE = block(VoxelizedFurnitureModBlocks.BAMBOO_PORCH_TABLE, "bamboo_porch_table", new Item.Properties().fireResistant());
		ACACIA_PORCH_TABLE = block(VoxelizedFurnitureModBlocks.ACACIA_PORCH_TABLE, "acacia_porch_table", new Item.Properties().fireResistant());
		AMETHYST_GEODE = block(VoxelizedFurnitureModBlocks.AMETHYST_GEODE, "amethyst_geode", new Item.Properties().fireResistant());
		EMERALD_GEODE = block(VoxelizedFurnitureModBlocks.EMERALD_GEODE, "emerald_geode", new Item.Properties().fireResistant());
		DIAMOND_GEODE = block(VoxelizedFurnitureModBlocks.DIAMOND_GEODE, "diamond_geode", new Item.Properties().fireResistant());
		REDSTONE_GEODE = block(VoxelizedFurnitureModBlocks.REDSTONE_GEODE, "redstone_geode", new Item.Properties().fireResistant());
		MINIATURE_RUINED_NETHER_PORTAL = block(VoxelizedFurnitureModBlocks.MINIATURE_RUINED_NETHER_PORTAL, "miniature_ruined_nether_portal", new Item.Properties().fireResistant());
		MINIATURE_WATER_RUIN = block(VoxelizedFurnitureModBlocks.MINIATURE_WATER_RUIN, "miniature_water_ruin", new Item.Properties().fireResistant());
		OAK_TOILET_ROLL = block(VoxelizedFurnitureModBlocks.OAK_TOILET_ROLL, "oak_toilet_roll");
		SPRUCE_TOILET_ROLL = block(VoxelizedFurnitureModBlocks.SPRUCE_TOILET_ROLL, "spruce_toilet_roll");
		MANGROVE_TOILET_ROLL = block(VoxelizedFurnitureModBlocks.MANGROVE_TOILET_ROLL, "mangrove_toilet_roll");
		JUNGLE_TOILET_ROLL = block(VoxelizedFurnitureModBlocks.JUNGLE_TOILET_ROLL, "jungle_toilet_roll");
		DARK_OAK_TOILET_ROLL = block(VoxelizedFurnitureModBlocks.DARK_OAK_TOILET_ROLL, "dark_oak_toilet_roll");
		CHERRY_TOILET_ROLL = block(VoxelizedFurnitureModBlocks.CHERRY_TOILET_ROLL, "cherry_toilet_roll");
		BIRCH_TOILET_ROLL = block(VoxelizedFurnitureModBlocks.BIRCH_TOILET_ROLL, "birch_toilet_roll");
		BAMBOO_TOILET_ROLL = block(VoxelizedFurnitureModBlocks.BAMBOO_TOILET_ROLL, "bamboo_toilet_roll");
		ACACIA_TOILET_ROLL = block(VoxelizedFurnitureModBlocks.ACACIA_TOILET_ROLL, "acacia_toilet_roll");
		GREEN_BAMBOO_PLANT = block(VoxelizedFurnitureModBlocks.GREEN_BAMBOO_PLANT, "green_bamboo_plant", new Item.Properties().fireResistant());
		BARREL_PLANT = block(VoxelizedFurnitureModBlocks.BARREL_PLANT, "barrel_plant");
		SEED_IN_POT = block(VoxelizedFurnitureModBlocks.SEED_IN_POT, "seed_in_pot", new Item.Properties().fireResistant());
		SEED_IN_POT_RAMDOM = block(VoxelizedFurnitureModBlocks.SEED_IN_POT_RAMDOM, "seed_in_pot_ramdom", new Item.Properties().fireResistant());
		CUBE_CEILING_LIGHT = block(VoxelizedFurnitureModBlocks.CUBE_CEILING_LIGHT, "cube_ceiling_light", new Item.Properties().fireResistant());
		YUCCA_PLANT = block(VoxelizedFurnitureModBlocks.YUCCA_PLANT, "yucca_plant");
		YUCCA_PLANT_RANDOM = block(VoxelizedFurnitureModBlocks.YUCCA_PLANT_RANDOM, "yucca_plant_random");
		WHEAT_PLANT = block(VoxelizedFurnitureModBlocks.WHEAT_PLANT, "wheat_plant", new Item.Properties().fireResistant());
		RANDOM_WHEAT_PLANT = block(VoxelizedFurnitureModBlocks.RANDOM_WHEAT_PLANT, "random_wheat_plant", new Item.Properties().fireResistant());
		BRICKS = block(VoxelizedFurnitureModBlocks.BRICKS, "bricks", new Item.Properties().fireResistant());
		CACTUS_PLANT = block(VoxelizedFurnitureModBlocks.CACTUS_PLANT, "cactus_plant", new Item.Properties().fireResistant());
		CACTUS_PLANT_RANDOM = block(VoxelizedFurnitureModBlocks.CACTUS_PLANT_RANDOM, "cactus_plant_random", new Item.Properties().fireResistant());
		OAK_DRAWER = block(VoxelizedFurnitureModBlocks.OAK_DRAWER, "oak_drawer");
		SPRUCE_DRAWER = block(VoxelizedFurnitureModBlocks.SPRUCE_DRAWER, "spruce_drawer");
		JUNGLE_DRAWER = block(VoxelizedFurnitureModBlocks.JUNGLE_DRAWER, "jungle_drawer");
		DARK_OAK_DRAWER = block(VoxelizedFurnitureModBlocks.DARK_OAK_DRAWER, "dark_oak_drawer");
		CHERRY_DRAWER = block(VoxelizedFurnitureModBlocks.CHERRY_DRAWER, "cherry_drawer");
		BIRCH_DRAWER = block(VoxelizedFurnitureModBlocks.BIRCH_DRAWER, "birch_drawer");
		BAMBOO_DRAWER = block(VoxelizedFurnitureModBlocks.BAMBOO_DRAWER, "bamboo_drawer");
		ACACIA_DRAWER = block(VoxelizedFurnitureModBlocks.ACACIA_DRAWER, "acacia_drawer");
		MANGROVE_DRAWER = block(VoxelizedFurnitureModBlocks.MANGROVE_DRAWER, "mangrove_drawer");
		KYANITE = block(VoxelizedFurnitureModBlocks.KYANITE, "kyanite", new Item.Properties().fireResistant());
		BAMBOO_CLUSTER = block(VoxelizedFurnitureModBlocks.BAMBOO_CLUSTER, "bamboo_cluster");
		PAN = block(VoxelizedFurnitureModBlocks.PAN, "pan", new Item.Properties().fireResistant());
		AIRFRYER = block(VoxelizedFurnitureModBlocks.AIRFRYER, "airfryer");
		MICROWAVE = block(VoxelizedFurnitureModBlocks.MICROWAVE, "microwave", new Item.Properties().fireResistant());
		TOASTER_WHITE = block(VoxelizedFurnitureModBlocks.TOASTER_WHITE, "toaster_white", new Item.Properties().fireResistant());
		TOASTER_BLUE = block(VoxelizedFurnitureModBlocks.TOASTER_BLUE, "toaster_blue", new Item.Properties().fireResistant());
		TOASTER_BROWN = block(VoxelizedFurnitureModBlocks.TOASTER_BROWN, "toaster_brown", new Item.Properties().fireResistant());
		TOASTER_CYAN = block(VoxelizedFurnitureModBlocks.TOASTER_CYAN, "toaster_cyan", new Item.Properties().fireResistant());
		TOASTER_GRAY = block(VoxelizedFurnitureModBlocks.TOASTER_GRAY, "toaster_gray", new Item.Properties().fireResistant());
		TOASTER_GREEN = block(VoxelizedFurnitureModBlocks.TOASTER_GREEN, "toaster_green", new Item.Properties().fireResistant());
		TOASTER_LIGHT_BLUE = block(VoxelizedFurnitureModBlocks.TOASTER_LIGHT_BLUE, "toaster_light_blue", new Item.Properties().fireResistant());
		TOASTER_LIGHT_GRAY = block(VoxelizedFurnitureModBlocks.TOASTER_LIGHT_GRAY, "toaster_light_gray", new Item.Properties().fireResistant());
		TOASTER_LIME = block(VoxelizedFurnitureModBlocks.TOASTER_LIME, "toaster_lime", new Item.Properties().fireResistant());
		TOASTER_MAGENTA = block(VoxelizedFurnitureModBlocks.TOASTER_MAGENTA, "toaster_magenta", new Item.Properties().fireResistant());
		TOASTER_ORANGE = block(VoxelizedFurnitureModBlocks.TOASTER_ORANGE, "toaster_orange", new Item.Properties().fireResistant());
		TOASTER_PINK = block(VoxelizedFurnitureModBlocks.TOASTER_PINK, "toaster_pink", new Item.Properties().fireResistant());
		TOASTER_PURPLE = block(VoxelizedFurnitureModBlocks.TOASTER_PURPLE, "toaster_purple", new Item.Properties().fireResistant());
		TOASTER_RED = block(VoxelizedFurnitureModBlocks.TOASTER_RED, "toaster_red", new Item.Properties().fireResistant());
		TOASTER_YELLOW = block(VoxelizedFurnitureModBlocks.TOASTER_YELLOW, "toaster_yellow", new Item.Properties().fireResistant());
		WOODEN_CRATE = block(VoxelizedFurnitureModBlocks.WOODEN_CRATE, "wooden_crate");
		SACK_OF_SOIL = block(VoxelizedFurnitureModBlocks.SACK_OF_SOIL, "sack_of_soil", new Item.Properties().fireResistant());
		GRAY_WATERING_CAN = block(VoxelizedFurnitureModBlocks.GRAY_WATERING_CAN, "gray_watering_can", new Item.Properties().fireResistant());
		BLUE_WATERING_CAN = block(VoxelizedFurnitureModBlocks.BLUE_WATERING_CAN, "blue_watering_can", new Item.Properties().fireResistant());
		GREEN_WATERING_CAN = block(VoxelizedFurnitureModBlocks.GREEN_WATERING_CAN, "green_watering_can", new Item.Properties().fireResistant());
		WOODEN_KITCHEN_DRAWER = block(VoxelizedFurnitureModBlocks.WOODEN_KITCHEN_DRAWER, "wooden_kitchen_drawer");
		WOODEN_OVEN_COOKTOP = block(VoxelizedFurnitureModBlocks.WOODEN_OVEN_COOKTOP, "wooden_oven_cooktop");
		WOODEN_KITCHEN_SINK = block(VoxelizedFurnitureModBlocks.WOODEN_KITCHEN_SINK, "wooden_kitchen_sink");
		SOFT_OAK = block(VoxelizedFurnitureModBlocks.SOFT_OAK, "soft_oak");
		SOFT_PALE_OAK = block(VoxelizedFurnitureModBlocks.SOFT_PALE_OAK, "soft_pale_oak");
		SOFT_DARK_OAK = block(VoxelizedFurnitureModBlocks.SOFT_DARK_OAK, "soft_dark_oak");
		WOODEN_KITCHEN_EXHAUSTHOOD = block(VoxelizedFurnitureModBlocks.WOODEN_KITCHEN_EXHAUSTHOOD, "wooden_kitchen_exhausthood");
		WOODEN_KITCHEN_CABINET_ABOVE = block(VoxelizedFurnitureModBlocks.WOODEN_KITCHEN_CABINET_ABOVE, "wooden_kitchen_cabinet_above");
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> I register(String name, Function<Item.Properties, ? extends I> supplier) {
		return (I) Items.registerItem(ResourceKey.create(Registries.ITEM, Identifier.fromNamespaceAndPath(VoxelizedFurnitureMod.MODID, name)), (Function<Item.Properties, Item>) supplier);
	}

	private static Item block(Block block, String name) {
		return block(block, name, new Item.Properties());
	}

	private static Item block(Block block, String name, Item.Properties properties) {
		return Items.registerItem(ResourceKey.create(Registries.ITEM, Identifier.fromNamespaceAndPath(VoxelizedFurnitureMod.MODID, name)), prop -> new BlockItem(block, prop), properties);
	}
}