/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.okil.voxelizedfurniture.init;

import net.okil.voxelizedfurniture.item.JamBottleItem;
import net.okil.voxelizedfurniture.block.display.AwningDisplayItem;
import net.okil.voxelizedfurniture.VoxelizedFurnitureMod;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

public class VoxelizedFurnitureModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(VoxelizedFurnitureMod.MODID);
	public static final DeferredItem<Item> CABINET_OAK = block(VoxelizedFurnitureModBlocks.CABINET_OAK);
	public static final DeferredItem<Item> CABINET_BIRCH = block(VoxelizedFurnitureModBlocks.CABINET_BIRCH);
	public static final DeferredItem<Item> CABINET_DARK_OAK = block(VoxelizedFurnitureModBlocks.CABINET_DARK_OAK);
	public static final DeferredItem<Item> CABINET_ACACIA = block(VoxelizedFurnitureModBlocks.CABINET_ACACIA);
	public static final DeferredItem<Item> CABINET_MANGROVE = block(VoxelizedFurnitureModBlocks.CABINET_MANGROVE);
	public static final DeferredItem<Item> CABINET_CHERRY = block(VoxelizedFurnitureModBlocks.CABINET_CHERRY);
	public static final DeferredItem<Item> CABINET_JUNGLE = block(VoxelizedFurnitureModBlocks.CABINET_JUNGLE);
	public static final DeferredItem<Item> CABINET_BAMBOO = block(VoxelizedFurnitureModBlocks.CABINET_BAMBOO);
	public static final DeferredItem<Item> FRIDGE = block(VoxelizedFurnitureModBlocks.FRIDGE);
	public static final DeferredItem<Item> OAK_SINK = block(VoxelizedFurnitureModBlocks.OAK_SINK);
	public static final DeferredItem<Item> SPRUCE_SINK = block(VoxelizedFurnitureModBlocks.SPRUCE_SINK);
	public static final DeferredItem<Item> MANGROVE_SINK = block(VoxelizedFurnitureModBlocks.MANGROVE_SINK);
	public static final DeferredItem<Item> JUNGLE_SINK = block(VoxelizedFurnitureModBlocks.JUNGLE_SINK);
	public static final DeferredItem<Item> DARK_OAK_SINK = block(VoxelizedFurnitureModBlocks.DARK_OAK_SINK);
	public static final DeferredItem<Item> BIRCH_SINK = block(VoxelizedFurnitureModBlocks.BIRCH_SINK);
	public static final DeferredItem<Item> ACACIA_SINK = block(VoxelizedFurnitureModBlocks.ACACIA_SINK);
	public static final DeferredItem<Item> CHERRY_SINK = block(VoxelizedFurnitureModBlocks.CHERRY_SINK);
	public static final DeferredItem<Item> BAMBOO_SINK = block(VoxelizedFurnitureModBlocks.BAMBOO_SINK);
	public static final DeferredItem<Item> CABINET_SPRUCE = block(VoxelizedFurnitureModBlocks.CABINET_SPRUCE);
	public static final DeferredItem<Item> JAM_JAR = block(VoxelizedFurnitureModBlocks.JAM_JAR);
	public static final DeferredItem<Item> HONEY_JAR = block(VoxelizedFurnitureModBlocks.HONEY_JAR);
	public static final DeferredItem<Item> JAM_BOTTLE = REGISTRY.register("jam_bottle", JamBottleItem::new);
	public static final DeferredItem<Item> SHOWER = block(VoxelizedFurnitureModBlocks.SHOWER);
	public static final DeferredItem<Item> OAK_SHELF = block(VoxelizedFurnitureModBlocks.OAK_SHELF);
	public static final DeferredItem<Item> SPRUCE_SHELF = block(VoxelizedFurnitureModBlocks.SPRUCE_SHELF);
	public static final DeferredItem<Item> MANGROVE_SHELF = block(VoxelizedFurnitureModBlocks.MANGROVE_SHELF);
	public static final DeferredItem<Item> JUNGLE_SHELF = block(VoxelizedFurnitureModBlocks.JUNGLE_SHELF);
	public static final DeferredItem<Item> DARK_OAK_SHELF = block(VoxelizedFurnitureModBlocks.DARK_OAK_SHELF);
	public static final DeferredItem<Item> CHERRY_SHELF = block(VoxelizedFurnitureModBlocks.CHERRY_SHELF);
	public static final DeferredItem<Item> BIRCH_SHELF = block(VoxelizedFurnitureModBlocks.BIRCH_SHELF);
	public static final DeferredItem<Item> BAMBOO_SHELF = block(VoxelizedFurnitureModBlocks.BAMBOO_SHELF);
	public static final DeferredItem<Item> ACACIA_SHELF = block(VoxelizedFurnitureModBlocks.ACACIA_SHELF);
	public static final DeferredItem<Item> SOAP = block(VoxelizedFurnitureModBlocks.SOAP);
	public static final DeferredItem<Item> OAK_CHAIR_1 = block(VoxelizedFurnitureModBlocks.OAK_CHAIR_1);
	public static final DeferredItem<Item> SPRUCE_CHAIR_1 = block(VoxelizedFurnitureModBlocks.SPRUCE_CHAIR_1);
	public static final DeferredItem<Item> MANGROVE_CHAIR_1 = block(VoxelizedFurnitureModBlocks.MANGROVE_CHAIR_1);
	public static final DeferredItem<Item> JUNGLE_CHAIR_1 = block(VoxelizedFurnitureModBlocks.JUNGLE_CHAIR_1);
	public static final DeferredItem<Item> DARK_OAK_CHAIR_1 = block(VoxelizedFurnitureModBlocks.DARK_OAK_CHAIR_1);
	public static final DeferredItem<Item> CHERRY_CHAIR_1 = block(VoxelizedFurnitureModBlocks.CHERRY_CHAIR_1);
	public static final DeferredItem<Item> BIRCH_CHAIR_1 = block(VoxelizedFurnitureModBlocks.BIRCH_CHAIR_1);
	public static final DeferredItem<Item> BAMBOO_CHAIR_1 = block(VoxelizedFurnitureModBlocks.BAMBOO_CHAIR_1);
	public static final DeferredItem<Item> ACACIA_CHAIR_1 = block(VoxelizedFurnitureModBlocks.ACACIA_CHAIR_1);
	public static final DeferredItem<Item> GROUND_DEV_TEX = block(VoxelizedFurnitureModBlocks.GROUND_DEV_TEX);
	public static final DeferredItem<Item> GOLDEN_DESKTOP_FOUNTAIN = block(VoxelizedFurnitureModBlocks.GOLDEN_DESKTOP_FOUNTAIN);
	public static final DeferredItem<Item> POTTED_GREEN_PLANT = block(VoxelizedFurnitureModBlocks.POTTED_GREEN_PLANT);
	public static final DeferredItem<Item> GOLDEN_ZEN_FOUNTAIN = block(VoxelizedFurnitureModBlocks.GOLDEN_ZEN_FOUNTAIN);
	public static final DeferredItem<Item> TV = block(VoxelizedFurnitureModBlocks.TV);
	public static final DeferredItem<Item> LAPTOP = block(VoxelizedFurnitureModBlocks.LAPTOP);
	public static final DeferredItem<Item> ASPHALT = block(VoxelizedFurnitureModBlocks.ASPHALT);
	public static final DeferredItem<Item> DOUBLE_BED = block(VoxelizedFurnitureModBlocks.DOUBLE_BED);
	public static final DeferredItem<Item> SINGLE_BED = block(VoxelizedFurnitureModBlocks.SINGLE_BED);
	public static final DeferredItem<Item> OAK_WARDROBE = block(VoxelizedFurnitureModBlocks.OAK_WARDROBE);
	public static final DeferredItem<Item> SPRUCE_WARDROBE = block(VoxelizedFurnitureModBlocks.SPRUCE_WARDROBE);
	public static final DeferredItem<Item> MANGROVE_WARDROBE = block(VoxelizedFurnitureModBlocks.MANGROVE_WARDROBE);
	public static final DeferredItem<Item> JUNGLE_WARDROBE = block(VoxelizedFurnitureModBlocks.JUNGLE_WARDROBE);
	public static final DeferredItem<Item> DARK_OAK_WARDROBE = block(VoxelizedFurnitureModBlocks.DARK_OAK_WARDROBE);
	public static final DeferredItem<Item> CHERRY_WARDROBE = block(VoxelizedFurnitureModBlocks.CHERRY_WARDROBE);
	public static final DeferredItem<Item> BIRCH_WARDROBE = block(VoxelizedFurnitureModBlocks.BIRCH_WARDROBE);
	public static final DeferredItem<Item> BAMBOO_WARDROBE = block(VoxelizedFurnitureModBlocks.BAMBOO_WARDROBE);
	public static final DeferredItem<Item> ACACIA_WARDROBE = block(VoxelizedFurnitureModBlocks.ACACIA_WARDROBE);
	public static final DeferredItem<Item> LIGHT = block(VoxelizedFurnitureModBlocks.LIGHT);
	public static final DeferredItem<Item> LIGHT_SWITCH_BUTTON = block(VoxelizedFurnitureModBlocks.LIGHT_SWITCH_BUTTON);
	public static final DeferredItem<Item> BROWN_BARBECUE = block(VoxelizedFurnitureModBlocks.BROWN_BARBECUE);
	public static final DeferredItem<Item> KITCHEN_DRAWER = block(VoxelizedFurnitureModBlocks.KITCHEN_DRAWER);
	public static final DeferredItem<Item> KITCHEN_DRAWER_1 = block(VoxelizedFurnitureModBlocks.KITCHEN_DRAWER_1);
	public static final DeferredItem<Item> KITCHEN_SINK = block(VoxelizedFurnitureModBlocks.KITCHEN_SINK);
	public static final DeferredItem<Item> OVEN = block(VoxelizedFurnitureModBlocks.OVEN);
	public static final DeferredItem<Item> OVEN_VENT = block(VoxelizedFurnitureModBlocks.OVEN_VENT);
	public static final DeferredItem<Item> KITCHEN_TABLE = block(VoxelizedFurnitureModBlocks.KITCHEN_TABLE);
	public static final DeferredItem<Item> KITCHEN_DRAWER_CORNER = block(VoxelizedFurnitureModBlocks.KITCHEN_DRAWER_CORNER);
	public static final DeferredItem<Item> KITCHEN_FRIDGE = block(VoxelizedFurnitureModBlocks.KITCHEN_FRIDGE);
	public static final DeferredItem<Item> MODERN_BULKHEAD_LIGHT_OFF = block(VoxelizedFurnitureModBlocks.MODERN_BULKHEAD_LIGHT_OFF);
	public static final DeferredItem<Item> OAK_COBBLE_PATH = block(VoxelizedFurnitureModBlocks.OAK_COBBLE_PATH);
	public static final DeferredItem<Item> SPRUCE_COBBLE_PATH = block(VoxelizedFurnitureModBlocks.SPRUCE_COBBLE_PATH);
	public static final DeferredItem<Item> MANGROVE_COBBLE_PATH = block(VoxelizedFurnitureModBlocks.MANGROVE_COBBLE_PATH);
	public static final DeferredItem<Item> JUNGLE_COBBLE_PATH = block(VoxelizedFurnitureModBlocks.JUNGLE_COBBLE_PATH);
	public static final DeferredItem<Item> DARK_OAK_COBBLE_PATH = block(VoxelizedFurnitureModBlocks.DARK_OAK_COBBLE_PATH);
	public static final DeferredItem<Item> CHERRY_COBBLE_PATH = block(VoxelizedFurnitureModBlocks.CHERRY_COBBLE_PATH);
	public static final DeferredItem<Item> BIRCH_COBBLE_PATH = block(VoxelizedFurnitureModBlocks.BIRCH_COBBLE_PATH);
	public static final DeferredItem<Item> BAMBOO_COBBLE_PATH = block(VoxelizedFurnitureModBlocks.BAMBOO_COBBLE_PATH);
	public static final DeferredItem<Item> ACACIA_COBBLE_PATH = block(VoxelizedFurnitureModBlocks.ACACIA_COBBLE_PATH);
	public static final DeferredItem<Item> OAK_DOORBELL = block(VoxelizedFurnitureModBlocks.OAK_DOORBELL);
	public static final DeferredItem<Item> SPRUCE_DOORBELL = block(VoxelizedFurnitureModBlocks.SPRUCE_DOORBELL);
	public static final DeferredItem<Item> MANGROVE_DOORBELL = block(VoxelizedFurnitureModBlocks.MANGROVE_DOORBELL);
	public static final DeferredItem<Item> JUNGLE_DOORBELL = block(VoxelizedFurnitureModBlocks.JUNGLE_DOORBELL);
	public static final DeferredItem<Item> DARK_OAK_DOORBELL = block(VoxelizedFurnitureModBlocks.DARK_OAK_DOORBELL);
	public static final DeferredItem<Item> CHERRY_DOORBELL = block(VoxelizedFurnitureModBlocks.CHERRY_DOORBELL);
	public static final DeferredItem<Item> BIRCH_DOORBELL = block(VoxelizedFurnitureModBlocks.BIRCH_DOORBELL);
	public static final DeferredItem<Item> BAMBOO_DOORBELL = block(VoxelizedFurnitureModBlocks.BAMBOO_DOORBELL);
	public static final DeferredItem<Item> ACACIA_DOORBELL = block(VoxelizedFurnitureModBlocks.ACACIA_DOORBELL);
	public static final DeferredItem<Item> OAK_PORCH_TABLE = block(VoxelizedFurnitureModBlocks.OAK_PORCH_TABLE);
	public static final DeferredItem<Item> SPRUCE_PORCH_TABLE = block(VoxelizedFurnitureModBlocks.SPRUCE_PORCH_TABLE);
	public static final DeferredItem<Item> MANGROVE_PORCH_TABLE = block(VoxelizedFurnitureModBlocks.MANGROVE_PORCH_TABLE);
	public static final DeferredItem<Item> JUNGLE_PORCH_TABLE = block(VoxelizedFurnitureModBlocks.JUNGLE_PORCH_TABLE);
	public static final DeferredItem<Item> DARK_OAK_PORCH_TABLE = block(VoxelizedFurnitureModBlocks.DARK_OAK_PORCH_TABLE);
	public static final DeferredItem<Item> CHERRY_PORCH_TABLE = block(VoxelizedFurnitureModBlocks.CHERRY_PORCH_TABLE);
	public static final DeferredItem<Item> BIRCH_PORCH_TABLE = block(VoxelizedFurnitureModBlocks.BIRCH_PORCH_TABLE);
	public static final DeferredItem<Item> BAMBOO_PORCH_TABLE = block(VoxelizedFurnitureModBlocks.BAMBOO_PORCH_TABLE);
	public static final DeferredItem<Item> ACACIA_PORCH_TABLE = block(VoxelizedFurnitureModBlocks.ACACIA_PORCH_TABLE);
	public static final DeferredItem<Item> AMETHYST_GEODE = block(VoxelizedFurnitureModBlocks.AMETHYST_GEODE);
	public static final DeferredItem<Item> EMERALD_GEODE = block(VoxelizedFurnitureModBlocks.EMERALD_GEODE);
	public static final DeferredItem<Item> DIAMOND_GEODE = block(VoxelizedFurnitureModBlocks.DIAMOND_GEODE);
	public static final DeferredItem<Item> REDSTONE_GEODE = block(VoxelizedFurnitureModBlocks.REDSTONE_GEODE);
	public static final DeferredItem<Item> MINIATURE_RUINED_NETHER_PORTAL = block(VoxelizedFurnitureModBlocks.MINIATURE_RUINED_NETHER_PORTAL);
	public static final DeferredItem<Item> MINIATURE_WATER_RUIN = block(VoxelizedFurnitureModBlocks.MINIATURE_WATER_RUIN);
	public static final DeferredItem<Item> OAK_TOILET_ROLL = block(VoxelizedFurnitureModBlocks.OAK_TOILET_ROLL);
	public static final DeferredItem<Item> SPRUCE_TOILET_ROLL = block(VoxelizedFurnitureModBlocks.SPRUCE_TOILET_ROLL);
	public static final DeferredItem<Item> MANGROVE_TOILET_ROLL = block(VoxelizedFurnitureModBlocks.MANGROVE_TOILET_ROLL);
	public static final DeferredItem<Item> JUNGLE_TOILET_ROLL = block(VoxelizedFurnitureModBlocks.JUNGLE_TOILET_ROLL);
	public static final DeferredItem<Item> DARK_OAK_TOILET_ROLL = block(VoxelizedFurnitureModBlocks.DARK_OAK_TOILET_ROLL);
	public static final DeferredItem<Item> CHERRY_TOILET_ROLL = block(VoxelizedFurnitureModBlocks.CHERRY_TOILET_ROLL);
	public static final DeferredItem<Item> BIRCH_TOILET_ROLL = block(VoxelizedFurnitureModBlocks.BIRCH_TOILET_ROLL);
	public static final DeferredItem<Item> BAMBOO_TOILET_ROLL = block(VoxelizedFurnitureModBlocks.BAMBOO_TOILET_ROLL);
	public static final DeferredItem<Item> ACACIA_TOILET_ROLL = block(VoxelizedFurnitureModBlocks.ACACIA_TOILET_ROLL);
	public static final DeferredItem<Item> GREEN_BAMBOO_PLANT = block(VoxelizedFurnitureModBlocks.GREEN_BAMBOO_PLANT);
	public static final DeferredItem<Item> BARREL_PLANT = block(VoxelizedFurnitureModBlocks.BARREL_PLANT);
	public static final DeferredItem<Item> SEED_IN_POT = block(VoxelizedFurnitureModBlocks.SEED_IN_POT);
	public static final DeferredItem<Item> BATHROOM_SET = block(VoxelizedFurnitureModBlocks.BATHROOM_SET);
	public static final DeferredItem<Item> NATURE_SET = block(VoxelizedFurnitureModBlocks.NATURE_SET);
	public static final DeferredItem<Item> FOOD_SET = block(VoxelizedFurnitureModBlocks.FOOD_SET);
	public static final DeferredItem<Item> KITCHEN_SET = block(VoxelizedFurnitureModBlocks.KITCHEN_SET);
	public static final DeferredItem<Item> SEED_IN_POT_RAMDOM = block(VoxelizedFurnitureModBlocks.SEED_IN_POT_RAMDOM);
	public static final DeferredItem<Item> CUBE_CEILING_LIGHT = block(VoxelizedFurnitureModBlocks.CUBE_CEILING_LIGHT);
	public static final DeferredItem<Item> YUCCA_PLANT = block(VoxelizedFurnitureModBlocks.YUCCA_PLANT);
	public static final DeferredItem<Item> YUCCA_PLANT_RANDOM = block(VoxelizedFurnitureModBlocks.YUCCA_PLANT_RANDOM);
	public static final DeferredItem<Item> WHEAT_PLANT = block(VoxelizedFurnitureModBlocks.WHEAT_PLANT);
	public static final DeferredItem<Item> RANDOM_WHEAT_PLANT = block(VoxelizedFurnitureModBlocks.RANDOM_WHEAT_PLANT);
	public static final DeferredItem<Item> BRICKS = block(VoxelizedFurnitureModBlocks.BRICKS);
	public static final DeferredItem<Item> AWNING = REGISTRY.register(VoxelizedFurnitureModBlocks.AWNING.getId().getPath(), () -> new AwningDisplayItem(VoxelizedFurnitureModBlocks.AWNING.get(), new Item.Properties()));
	public static final DeferredItem<Item> AWNING_CLOSED = block(VoxelizedFurnitureModBlocks.AWNING_CLOSED);
	public static final DeferredItem<Item> CACTUS_PLANT = block(VoxelizedFurnitureModBlocks.CACTUS_PLANT);

	// Start of user code block custom items
	// End of user code block custom items
	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}