/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.okil.voxelizedfurniture.init;

import net.okil.voxelizedfurniture.block.*;
import net.okil.voxelizedfurniture.VoxelizedFurnitureMod;

import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.Block;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.Identifier;
import net.minecraft.core.registries.Registries;

import java.util.function.Function;

public class VoxelizedFurnitureModBlocks {
	public static Block CABINET_OAK;
	public static Block CABINET_BIRCH;
	public static Block CABINET_DARK_OAK;
	public static Block CABINET_ACACIA;
	public static Block CABINET_MANGROVE;
	public static Block CABINET_CHERRY;
	public static Block CABINET_JUNGLE;
	public static Block CABINET_BAMBOO;
	public static Block FRIDGE;
	public static Block OAK_SINK;
	public static Block SPRUCE_SINK;
	public static Block MANGROVE_SINK;
	public static Block JUNGLE_SINK;
	public static Block DARK_OAK_SINK;
	public static Block BIRCH_SINK;
	public static Block ACACIA_SINK;
	public static Block CHERRY_SINK;
	public static Block BAMBOO_SINK;
	public static Block CABINET_SPRUCE;
	public static Block JAM_JAR;
	public static Block HONEY_JAR;
	public static Block SHOWER;
	public static Block OAK_SHELF;
	public static Block SPRUCE_SHELF;
	public static Block MANGROVE_SHELF;
	public static Block JUNGLE_SHELF;
	public static Block DARK_OAK_SHELF;
	public static Block CHERRY_SHELF;
	public static Block BIRCH_SHELF;
	public static Block BAMBOO_SHELF;
	public static Block ACACIA_SHELF;
	public static Block SOAP;
	public static Block OAK_CHAIR_1;
	public static Block SPRUCE_CHAIR_1;
	public static Block MANGROVE_CHAIR_1;
	public static Block JUNGLE_CHAIR_1;
	public static Block DARK_OAK_CHAIR_1;
	public static Block CHERRY_CHAIR_1;
	public static Block BIRCH_CHAIR_1;
	public static Block BAMBOO_CHAIR_1;
	public static Block ACACIA_CHAIR_1;
	public static Block GROUND_DEV_TEX;
	public static Block GOLDEN_DESKTOP_FOUNTAIN;
	public static Block POTTED_GREEN_PLANT;
	public static Block GOLDEN_ZEN_FOUNTAIN;
	public static Block TV;
	public static Block LAPTOP;
	public static Block ASPHALT;
	public static Block DOUBLE_BED;
	public static Block SINGLE_BED;
	public static Block OAK_WARDROBE;
	public static Block SPRUCE_WARDROBE;
	public static Block MANGROVE_WARDROBE;
	public static Block JUNGLE_WARDROBE;
	public static Block DARK_OAK_WARDROBE;
	public static Block CHERRY_WARDROBE;
	public static Block BIRCH_WARDROBE;
	public static Block BAMBOO_WARDROBE;
	public static Block ACACIA_WARDROBE;
	public static Block LIGHT;
	public static Block LIGHT_SWITCH_BUTTON;
	public static Block KITCHEN_DRAWER;
	public static Block KITCHEN_DRAWER_1;
	public static Block KITCHEN_SINK;
	public static Block OVEN;
	public static Block OVEN_VENT;
	public static Block KITCHEN_TABLE;
	public static Block KITCHEN_DRAWER_CORNER;
	public static Block KITCHEN_FRIDGE;
	public static Block MODERN_BULKHEAD_LIGHT_OFF;
	public static Block OAK_COBBLE_PATH;
	public static Block SPRUCE_COBBLE_PATH;
	public static Block MANGROVE_COBBLE_PATH;
	public static Block JUNGLE_COBBLE_PATH;
	public static Block DARK_OAK_COBBLE_PATH;
	public static Block CHERRY_COBBLE_PATH;
	public static Block BIRCH_COBBLE_PATH;
	public static Block BAMBOO_COBBLE_PATH;
	public static Block ACACIA_COBBLE_PATH;
	public static Block OAK_DOORBELL;
	public static Block SPRUCE_DOORBELL;
	public static Block MANGROVE_DOORBELL;
	public static Block JUNGLE_DOORBELL;
	public static Block DARK_OAK_DOORBELL;
	public static Block CHERRY_DOORBELL;
	public static Block BIRCH_DOORBELL;
	public static Block BAMBOO_DOORBELL;
	public static Block ACACIA_DOORBELL;
	public static Block OAK_PORCH_TABLE;
	public static Block SPRUCE_PORCH_TABLE;
	public static Block MANGROVE_PORCH_TABLE;
	public static Block JUNGLE_PORCH_TABLE;
	public static Block DARK_OAK_PORCH_TABLE;
	public static Block CHERRY_PORCH_TABLE;
	public static Block BIRCH_PORCH_TABLE;
	public static Block BAMBOO_PORCH_TABLE;
	public static Block ACACIA_PORCH_TABLE;
	public static Block AMETHYST_GEODE;
	public static Block EMERALD_GEODE;
	public static Block DIAMOND_GEODE;
	public static Block REDSTONE_GEODE;
	public static Block MINIATURE_RUINED_NETHER_PORTAL;
	public static Block MINIATURE_WATER_RUIN;
	public static Block OAK_TOILET_ROLL;
	public static Block SPRUCE_TOILET_ROLL;
	public static Block MANGROVE_TOILET_ROLL;
	public static Block JUNGLE_TOILET_ROLL;
	public static Block DARK_OAK_TOILET_ROLL;
	public static Block CHERRY_TOILET_ROLL;
	public static Block BIRCH_TOILET_ROLL;
	public static Block BAMBOO_TOILET_ROLL;
	public static Block ACACIA_TOILET_ROLL;
	public static Block GREEN_BAMBOO_PLANT;
	public static Block BARREL_PLANT;
	public static Block SEED_IN_POT;
	public static Block SEED_IN_POT_RAMDOM;
	public static Block CUBE_CEILING_LIGHT;
	public static Block YUCCA_PLANT;
	public static Block YUCCA_PLANT_RANDOM;
	public static Block WHEAT_PLANT;
	public static Block RANDOM_WHEAT_PLANT;
	public static Block BRICKS;
	public static Block CACTUS_PLANT;
	public static Block CACTUS_PLANT_RANDOM;
	public static Block OAK_DRAWER;
	public static Block SPRUCE_DRAWER;
	public static Block JUNGLE_DRAWER;
	public static Block DARK_OAK_DRAWER;
	public static Block CHERRY_DRAWER;
	public static Block BIRCH_DRAWER;
	public static Block BAMBOO_DRAWER;
	public static Block ACACIA_DRAWER;
	public static Block MANGROVE_DRAWER;
	public static Block KYANITE;
	public static Block BAMBOO_CLUSTER;
	public static Block PAN;
	public static Block AIRFRYER;
	public static Block MICROWAVE;
	public static Block TOASTER_WHITE;
	public static Block TOASTER_BLUE;
	public static Block TOASTER_BROWN;
	public static Block TOASTER_CYAN;
	public static Block TOASTER_GRAY;
	public static Block TOASTER_GREEN;
	public static Block TOASTER_LIGHT_BLUE;
	public static Block TOASTER_LIGHT_GRAY;
	public static Block TOASTER_LIME;
	public static Block TOASTER_MAGENTA;
	public static Block TOASTER_ORANGE;
	public static Block TOASTER_PINK;
	public static Block TOASTER_PURPLE;
	public static Block TOASTER_RED;
	public static Block TOASTER_YELLOW;
	public static Block WOODEN_CRATE;
	public static Block SACK_OF_SOIL;
	public static Block GRAY_WATERING_CAN;
	public static Block BLUE_WATERING_CAN;
	public static Block GREEN_WATERING_CAN;
	public static Block WOODEN_KITCHEN_DRAWER;
	public static Block WOODEN_OVEN_COOKTOP;
	public static Block WOODEN_KITCHEN_SINK;
	public static Block SOFT_OAK;
	public static Block SOFT_PALE_OAK;
	public static Block SOFT_DARK_OAK;
	public static Block WOODEN_KITCHEN_EXHAUSTHOOD;
	public static Block WOODEN_KITCHEN_CABINET_ABOVE;

	public static void load() {
		CABINET_OAK = register("cabinet_oak", CabinetOakBlock::new);
		CABINET_BIRCH = register("cabinet_birch", CabinetBirchBlock::new);
		CABINET_DARK_OAK = register("cabinet_dark_oak", CabinetDarkOakBlock::new);
		CABINET_ACACIA = register("cabinet_acacia", CabinetAcaciaBlock::new);
		CABINET_MANGROVE = register("cabinet_mangrove", CabinetMangroveBlock::new);
		CABINET_CHERRY = register("cabinet_cherry", CabinetCherryBlock::new);
		CABINET_JUNGLE = register("cabinet_jungle", CabinetJungleBlock::new);
		CABINET_BAMBOO = register("cabinet_bamboo", CabinetBambooBlock::new);
		FRIDGE = register("fridge", FridgeBlock::new);
		OAK_SINK = register("oak_sink", OakSinkBlock::new);
		SPRUCE_SINK = register("spruce_sink", SpruceSinkBlock::new);
		MANGROVE_SINK = register("mangrove_sink", MangroveSinkBlock::new);
		JUNGLE_SINK = register("jungle_sink", JungleSinkBlock::new);
		DARK_OAK_SINK = register("dark_oak_sink", DarkOakSinkBlock::new);
		BIRCH_SINK = register("birch_sink", BirchSinkBlock::new);
		ACACIA_SINK = register("acacia_sink", AcaciaSinkBlock::new);
		CHERRY_SINK = register("cherry_sink", CherrySinkBlock::new);
		BAMBOO_SINK = register("bamboo_sink", BambooSinkBlock::new);
		CABINET_SPRUCE = register("cabinet_spruce", CabinetSpruceBlock::new);
		JAM_JAR = register("jam_jar", JamJarBlock::new);
		HONEY_JAR = register("honey_jar", HoneyJarBlock::new);
		SHOWER = register("shower", ShowerBlock::new);
		OAK_SHELF = register("oak_shelf", OakShelfBlock::new);
		SPRUCE_SHELF = register("spruce_shelf", SpruceShelfBlock::new);
		MANGROVE_SHELF = register("mangrove_shelf", MangroveShelfBlock::new);
		JUNGLE_SHELF = register("jungle_shelf", JungleShelfBlock::new);
		DARK_OAK_SHELF = register("dark_oak_shelf", DarkOakShelfBlock::new);
		CHERRY_SHELF = register("cherry_shelf", CherryShelfBlock::new);
		BIRCH_SHELF = register("birch_shelf", BirchShelfBlock::new);
		BAMBOO_SHELF = register("bamboo_shelf", BambooShelfBlock::new);
		ACACIA_SHELF = register("acacia_shelf", AcaciaShelfBlock::new);
		SOAP = register("soap", SoapBlock::new);
		OAK_CHAIR_1 = register("oak_chair_1", OakChair1Block::new);
		SPRUCE_CHAIR_1 = register("spruce_chair_1", SpruceChair1Block::new);
		MANGROVE_CHAIR_1 = register("mangrove_chair_1", MangroveChair1Block::new);
		JUNGLE_CHAIR_1 = register("jungle_chair_1", JungleChair1Block::new);
		DARK_OAK_CHAIR_1 = register("dark_oak_chair_1", DarkOakChair1Block::new);
		CHERRY_CHAIR_1 = register("cherry_chair_1", CherryChair1Block::new);
		BIRCH_CHAIR_1 = register("birch_chair_1", BirchChair1Block::new);
		BAMBOO_CHAIR_1 = register("bamboo_chair_1", BambooChair1Block::new);
		ACACIA_CHAIR_1 = register("acacia_chair_1", AcaciaChair1Block::new);
		GROUND_DEV_TEX = register("ground_dev_tex", GroundDevTexBlock::new);
		GOLDEN_DESKTOP_FOUNTAIN = register("golden_desktop_fountain", GoldenDesktopFountainBlock::new);
		POTTED_GREEN_PLANT = register("potted_green_plant", PottedGreenPlantBlock::new);
		GOLDEN_ZEN_FOUNTAIN = register("golden_zen_fountain", GoldenZenFountainBlock::new);
		TV = register("tv", TvBlock::new);
		LAPTOP = register("laptop", LaptopBlock::new);
		ASPHALT = register("asphalt", AsphaltBlock::new);
		DOUBLE_BED = register("double_bed", DoubleBedBlock::new);
		SINGLE_BED = register("single_bed", SingleBedBlock::new);
		OAK_WARDROBE = register("oak_wardrobe", OakWardrobeBlock::new);
		SPRUCE_WARDROBE = register("spruce_wardrobe", SpruceWardrobeBlock::new);
		MANGROVE_WARDROBE = register("mangrove_wardrobe", MangroveWardrobeBlock::new);
		JUNGLE_WARDROBE = register("jungle_wardrobe", JungleWardrobeBlock::new);
		DARK_OAK_WARDROBE = register("dark_oak_wardrobe", DarkOakWardrobeBlock::new);
		CHERRY_WARDROBE = register("cherry_wardrobe", CherryWardrobeBlock::new);
		BIRCH_WARDROBE = register("birch_wardrobe", BirchWardrobeBlock::new);
		BAMBOO_WARDROBE = register("bamboo_wardrobe", BambooWardrobeBlock::new);
		ACACIA_WARDROBE = register("acacia_wardrobe", AcaciaWardrobeBlock::new);
		LIGHT = register("light", LightBlock::new);
		LIGHT_SWITCH_BUTTON = register("light_switch_button", LightSwitchButtonBlock::new);
		KITCHEN_DRAWER = register("kitchen_drawer", KitchenDrawerBlock::new);
		KITCHEN_DRAWER_1 = register("kitchen_drawer_1", KitchenDrawer1Block::new);
		KITCHEN_SINK = register("kitchen_sink", KitchenSinkBlock::new);
		OVEN = register("oven", OvenBlock::new);
		OVEN_VENT = register("oven_vent", OvenVentBlock::new);
		KITCHEN_TABLE = register("kitchen_table", KitchenTableBlock::new);
		KITCHEN_DRAWER_CORNER = register("kitchen_drawer_corner", KitchenDrawerCornerBlock::new);
		KITCHEN_FRIDGE = register("kitchen_fridge", KitchenFridgeBlock::new);
		MODERN_BULKHEAD_LIGHT_OFF = register("modern_bulkhead_light_off", ModernBulkheadLightOffBlock::new);
		OAK_COBBLE_PATH = register("oak_cobble_path", OakCobblePathBlock::new);
		SPRUCE_COBBLE_PATH = register("spruce_cobble_path", SpruceCobblePathBlock::new);
		MANGROVE_COBBLE_PATH = register("mangrove_cobble_path", MangroveCobblePathBlock::new);
		JUNGLE_COBBLE_PATH = register("jungle_cobble_path", JungleCobblePathBlock::new);
		DARK_OAK_COBBLE_PATH = register("dark_oak_cobble_path", DarkOakCobblePathBlock::new);
		CHERRY_COBBLE_PATH = register("cherry_cobble_path", CherryCobblePathBlock::new);
		BIRCH_COBBLE_PATH = register("birch_cobble_path", BirchCobblePathBlock::new);
		BAMBOO_COBBLE_PATH = register("bamboo_cobble_path", BambooCobblePathBlock::new);
		ACACIA_COBBLE_PATH = register("acacia_cobble_path", AcaciaCobblePathBlock::new);
		OAK_DOORBELL = register("oak_doorbell", OakDoorbellBlock::new);
		SPRUCE_DOORBELL = register("spruce_doorbell", SpruceDoorbellBlock::new);
		MANGROVE_DOORBELL = register("mangrove_doorbell", MangroveDoorbellBlock::new);
		JUNGLE_DOORBELL = register("jungle_doorbell", JungleDoorbellBlock::new);
		DARK_OAK_DOORBELL = register("dark_oak_doorbell", DarkOakDoorbellBlock::new);
		CHERRY_DOORBELL = register("cherry_doorbell", CherryDoorbellBlock::new);
		BIRCH_DOORBELL = register("birch_doorbell", BirchDoorbellBlock::new);
		BAMBOO_DOORBELL = register("bamboo_doorbell", BambooDoorbellBlock::new);
		ACACIA_DOORBELL = register("acacia_doorbell", AcaciaDoorbellBlock::new);
		OAK_PORCH_TABLE = register("oak_porch_table", OakPorchTableBlock::new);
		SPRUCE_PORCH_TABLE = register("spruce_porch_table", SprucePorchTableBlock::new);
		MANGROVE_PORCH_TABLE = register("mangrove_porch_table", MangrovePorchTableBlock::new);
		JUNGLE_PORCH_TABLE = register("jungle_porch_table", JunglePorchTableBlock::new);
		DARK_OAK_PORCH_TABLE = register("dark_oak_porch_table", DarkOakPorchTableBlock::new);
		CHERRY_PORCH_TABLE = register("cherry_porch_table", CherryPorchTableBlock::new);
		BIRCH_PORCH_TABLE = register("birch_porch_table", BirchPorchTableBlock::new);
		BAMBOO_PORCH_TABLE = register("bamboo_porch_table", BambooPorchTableBlock::new);
		ACACIA_PORCH_TABLE = register("acacia_porch_table", AcaciaPorchTableBlock::new);
		AMETHYST_GEODE = register("amethyst_geode", AmethystGeodeBlock::new);
		EMERALD_GEODE = register("emerald_geode", EmeraldGeodeBlock::new);
		DIAMOND_GEODE = register("diamond_geode", DiamondGeodeBlock::new);
		REDSTONE_GEODE = register("redstone_geode", RedstoneGeodeBlock::new);
		MINIATURE_RUINED_NETHER_PORTAL = register("miniature_ruined_nether_portal", MiniatureRuinedNetherPortalBlock::new);
		MINIATURE_WATER_RUIN = register("miniature_water_ruin", MiniatureWaterRuinBlock::new);
		OAK_TOILET_ROLL = register("oak_toilet_roll", OakToiletRollBlock::new);
		SPRUCE_TOILET_ROLL = register("spruce_toilet_roll", SpruceToiletRollBlock::new);
		MANGROVE_TOILET_ROLL = register("mangrove_toilet_roll", MangroveToiletRollBlock::new);
		JUNGLE_TOILET_ROLL = register("jungle_toilet_roll", JungleToiletRollBlock::new);
		DARK_OAK_TOILET_ROLL = register("dark_oak_toilet_roll", DarkOakToiletRollBlock::new);
		CHERRY_TOILET_ROLL = register("cherry_toilet_roll", CherryToiletRollBlock::new);
		BIRCH_TOILET_ROLL = register("birch_toilet_roll", BirchToiletRollBlock::new);
		BAMBOO_TOILET_ROLL = register("bamboo_toilet_roll", BambooToiletRollBlock::new);
		ACACIA_TOILET_ROLL = register("acacia_toilet_roll", AcaciaToiletRollBlock::new);
		GREEN_BAMBOO_PLANT = register("green_bamboo_plant", GreenBambooPlantBlock::new);
		BARREL_PLANT = register("barrel_plant", BarrelPlantBlock::new);
		SEED_IN_POT = register("seed_in_pot", SeedInPotBlock::new);
		SEED_IN_POT_RAMDOM = register("seed_in_pot_ramdom", SeedInPotRamdomBlock::new);
		CUBE_CEILING_LIGHT = register("cube_ceiling_light", CubeCeilingLightBlock::new);
		YUCCA_PLANT = register("yucca_plant", YuccaPlantBlock::new);
		YUCCA_PLANT_RANDOM = register("yucca_plant_random", YuccaPlantRandomBlock::new);
		WHEAT_PLANT = register("wheat_plant", WheatPlantBlock::new);
		RANDOM_WHEAT_PLANT = register("random_wheat_plant", RandomWheatPlantBlock::new);
		BRICKS = register("bricks", BricksBlock::new);
		CACTUS_PLANT = register("cactus_plant", CactusPlantBlock::new);
		CACTUS_PLANT_RANDOM = register("cactus_plant_random", CactusPlantRandomBlock::new);
		OAK_DRAWER = register("oak_drawer", OakDrawerBlock::new);
		SPRUCE_DRAWER = register("spruce_drawer", SpruceDrawerBlock::new);
		JUNGLE_DRAWER = register("jungle_drawer", JungleDrawerBlock::new);
		DARK_OAK_DRAWER = register("dark_oak_drawer", DarkOakDrawerBlock::new);
		CHERRY_DRAWER = register("cherry_drawer", CherryDrawerBlock::new);
		BIRCH_DRAWER = register("birch_drawer", BirchDrawerBlock::new);
		BAMBOO_DRAWER = register("bamboo_drawer", BambooDrawerBlock::new);
		ACACIA_DRAWER = register("acacia_drawer", AcaciaDrawerBlock::new);
		MANGROVE_DRAWER = register("mangrove_drawer", MangroveDrawerBlock::new);
		KYANITE = register("kyanite", KyaniteBlock::new);
		BAMBOO_CLUSTER = register("bamboo_cluster", BambooClusterBlock::new);
		PAN = register("pan", PanBlock::new);
		AIRFRYER = register("airfryer", AirfryerBlock::new);
		MICROWAVE = register("microwave", MicrowaveBlock::new);
		TOASTER_WHITE = register("toaster_white", ToasterWhiteBlock::new);
		TOASTER_BLUE = register("toaster_blue", ToasterBlueBlock::new);
		TOASTER_BROWN = register("toaster_brown", ToasterBrownBlock::new);
		TOASTER_CYAN = register("toaster_cyan", ToasterCyanBlock::new);
		TOASTER_GRAY = register("toaster_gray", ToasterGrayBlock::new);
		TOASTER_GREEN = register("toaster_green", ToasterGreenBlock::new);
		TOASTER_LIGHT_BLUE = register("toaster_light_blue", ToasterLightBlueBlock::new);
		TOASTER_LIGHT_GRAY = register("toaster_light_gray", ToasterLightGrayBlock::new);
		TOASTER_LIME = register("toaster_lime", ToasterLimeBlock::new);
		TOASTER_MAGENTA = register("toaster_magenta", ToasterMagentaBlock::new);
		TOASTER_ORANGE = register("toaster_orange", ToasterOrangeBlock::new);
		TOASTER_PINK = register("toaster_pink", ToasterPinkBlock::new);
		TOASTER_PURPLE = register("toaster_purple", ToasterPurpleBlock::new);
		TOASTER_RED = register("toaster_red", ToasterRedBlock::new);
		TOASTER_YELLOW = register("toaster_yellow", ToasterYellowBlock::new);
		WOODEN_CRATE = register("wooden_crate", WoodenCrateBlock::new);
		SACK_OF_SOIL = register("sack_of_soil", SackOfSoilBlock::new);
		GRAY_WATERING_CAN = register("gray_watering_can", GrayWateringCanBlock::new);
		BLUE_WATERING_CAN = register("blue_watering_can", BlueWateringCanBlock::new);
		GREEN_WATERING_CAN = register("green_watering_can", GreenWateringCanBlock::new);
		WOODEN_KITCHEN_DRAWER = register("wooden_kitchen_drawer", WoodenKitchenDrawerBlock::new);
		WOODEN_OVEN_COOKTOP = register("wooden_oven_cooktop", WoodenOvenCooktopBlock::new);
		WOODEN_KITCHEN_SINK = register("wooden_kitchen_sink", WoodenKitchenSinkBlock::new);
		SOFT_OAK = register("soft_oak", SoftOakBlock::new);
		SOFT_PALE_OAK = register("soft_pale_oak", SoftPaleOakBlock::new);
		SOFT_DARK_OAK = register("soft_dark_oak", SoftDarkOakBlock::new);
		WOODEN_KITCHEN_EXHAUSTHOOD = register("wooden_kitchen_exhausthood", WoodenKitchenExhausthoodBlock::new);
		WOODEN_KITCHEN_CABINET_ABOVE = register("wooden_kitchen_cabinet_above", WoodenKitchenCabinetAboveBlock::new);
	}

	// Start of user code block custom blocks
	// End of user code block custom blocks
	private static <B extends Block> B register(String name, Function<BlockBehaviour.Properties, B> supplier) {
		return (B) Blocks.register(ResourceKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath(VoxelizedFurnitureMod.MODID, name)), (Function<BlockBehaviour.Properties, Block>) supplier, BlockBehaviour.Properties.of());
	}

	public static void clientLoad() {
		OakShelfBlock.blockColorLoad();
		SpruceShelfBlock.blockColorLoad();
		MangroveShelfBlock.blockColorLoad();
		JungleShelfBlock.blockColorLoad();
		DarkOakShelfBlock.blockColorLoad();
		CherryShelfBlock.blockColorLoad();
		BirchShelfBlock.blockColorLoad();
		BambooShelfBlock.blockColorLoad();
		AcaciaShelfBlock.blockColorLoad();
		GoldenDesktopFountainBlock.blockColorLoad();
		GoldenZenFountainBlock.blockColorLoad();
		MiniatureWaterRuinBlock.blockColorLoad();
	}
}