/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.okil.voxelizedfurniture.init;

import net.okil.voxelizedfurniture.block.entity.*;
import net.okil.voxelizedfurniture.VoxelizedFurnitureMod;

import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.Block;
import net.minecraft.resources.Identifier;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.Registry;

import net.fabricmc.fabric.api.object.builder.v1.block.entity.FabricBlockEntityTypeBuilder;

public class VoxelizedFurnitureModBlockEntities {
	public static BlockEntityType<CabinetOakBlockEntity> CABINET_OAK;
	public static BlockEntityType<CabinetBirchBlockEntity> CABINET_BIRCH;
	public static BlockEntityType<CabinetDarkOakBlockEntity> CABINET_DARK_OAK;
	public static BlockEntityType<CabinetAcaciaBlockEntity> CABINET_ACACIA;
	public static BlockEntityType<CabinetMangroveBlockEntity> CABINET_MANGROVE;
	public static BlockEntityType<CabinetCherryBlockEntity> CABINET_CHERRY;
	public static BlockEntityType<CabinetJungleBlockEntity> CABINET_JUNGLE;
	public static BlockEntityType<CabinetBambooBlockEntity> CABINET_BAMBOO;
	public static BlockEntityType<FridgeBlockEntity> FRIDGE;
	public static BlockEntityType<CabinetSpruceBlockEntity> CABINET_SPRUCE;
	public static BlockEntityType<ShowerBlockEntity> SHOWER;
	public static BlockEntityType<OakShelfBlockEntity> OAK_SHELF;
	public static BlockEntityType<SpruceShelfBlockEntity> SPRUCE_SHELF;
	public static BlockEntityType<MangroveShelfBlockEntity> MANGROVE_SHELF;
	public static BlockEntityType<JungleShelfBlockEntity> JUNGLE_SHELF;
	public static BlockEntityType<DarkOakShelfBlockEntity> DARK_OAK_SHELF;
	public static BlockEntityType<CherryShelfBlockEntity> CHERRY_SHELF;
	public static BlockEntityType<BirchShelfBlockEntity> BIRCH_SHELF;
	public static BlockEntityType<BambooShelfBlockEntity> BAMBOO_SHELF;
	public static BlockEntityType<AcaciaShelfBlockEntity> ACACIA_SHELF;
	public static BlockEntityType<OakChair1BlockEntity> OAK_CHAIR_1;
	public static BlockEntityType<SpruceChair1BlockEntity> SPRUCE_CHAIR_1;
	public static BlockEntityType<MangroveChair1BlockEntity> MANGROVE_CHAIR_1;
	public static BlockEntityType<JungleChair1BlockEntity> JUNGLE_CHAIR_1;
	public static BlockEntityType<DarkOakChair1BlockEntity> DARK_OAK_CHAIR_1;
	public static BlockEntityType<CherryChair1BlockEntity> CHERRY_CHAIR_1;
	public static BlockEntityType<BirchChair1BlockEntity> BIRCH_CHAIR_1;
	public static BlockEntityType<BambooChair1BlockEntity> BAMBOO_CHAIR_1;
	public static BlockEntityType<AcaciaChair1BlockEntity> ACACIA_CHAIR_1;
	public static BlockEntityType<OakWardrobeBlockEntity> OAK_WARDROBE;
	public static BlockEntityType<SpruceWardrobeBlockEntity> SPRUCE_WARDROBE;
	public static BlockEntityType<MangroveWardrobeBlockEntity> MANGROVE_WARDROBE;
	public static BlockEntityType<JungleWardrobeBlockEntity> JUNGLE_WARDROBE;
	public static BlockEntityType<DarkOakWardrobeBlockEntity> DARK_OAK_WARDROBE;
	public static BlockEntityType<CherryWardrobeBlockEntity> CHERRY_WARDROBE;
	public static BlockEntityType<BirchWardrobeBlockEntity> BIRCH_WARDROBE;
	public static BlockEntityType<BambooWardrobeBlockEntity> BAMBOO_WARDROBE;
	public static BlockEntityType<AcaciaWardrobeBlockEntity> ACACIA_WARDROBE;
	public static BlockEntityType<KitchenDrawerBlockEntity> KITCHEN_DRAWER;
	public static BlockEntityType<KitchenDrawer1BlockEntity> KITCHEN_DRAWER_1;
	public static BlockEntityType<KitchenSinkBlockEntity> KITCHEN_SINK;
	public static BlockEntityType<OvenBlockEntity> OVEN;
	public static BlockEntityType<OvenVentBlockEntity> OVEN_VENT;
	public static BlockEntityType<KitchenFridgeBlockEntity> KITCHEN_FRIDGE;
	public static BlockEntityType<CherryDoorbellBlockEntity> CHERRY_DOORBELL;
	public static BlockEntityType<BirchDoorbellBlockEntity> BIRCH_DOORBELL;
	public static BlockEntityType<BambooDoorbellBlockEntity> BAMBOO_DOORBELL;
	public static BlockEntityType<AcaciaDoorbellBlockEntity> ACACIA_DOORBELL;
	public static BlockEntityType<MangrovePorchTableBlockEntity> MANGROVE_PORCH_TABLE;
	public static BlockEntityType<JunglePorchTableBlockEntity> JUNGLE_PORCH_TABLE;
	public static BlockEntityType<DarkOakPorchTableBlockEntity> DARK_OAK_PORCH_TABLE;
	public static BlockEntityType<CherryPorchTableBlockEntity> CHERRY_PORCH_TABLE;
	public static BlockEntityType<BirchPorchTableBlockEntity> BIRCH_PORCH_TABLE;
	public static BlockEntityType<BambooPorchTableBlockEntity> BAMBOO_PORCH_TABLE;
	public static BlockEntityType<AcaciaPorchTableBlockEntity> ACACIA_PORCH_TABLE;
	public static BlockEntityType<SpruceToiletRollBlockEntity> SPRUCE_TOILET_ROLL;
	public static BlockEntityType<MangroveToiletRollBlockEntity> MANGROVE_TOILET_ROLL;
	public static BlockEntityType<JungleToiletRollBlockEntity> JUNGLE_TOILET_ROLL;
	public static BlockEntityType<DarkOakToiletRollBlockEntity> DARK_OAK_TOILET_ROLL;
	public static BlockEntityType<CherryToiletRollBlockEntity> CHERRY_TOILET_ROLL;
	public static BlockEntityType<BirchToiletRollBlockEntity> BIRCH_TOILET_ROLL;
	public static BlockEntityType<BambooToiletRollBlockEntity> BAMBOO_TOILET_ROLL;
	public static BlockEntityType<AcaciaToiletRollBlockEntity> ACACIA_TOILET_ROLL;
	public static BlockEntityType<SeedInPotBlockEntity> SEED_IN_POT;
	public static BlockEntityType<SeedInPotRamdomBlockEntity> SEED_IN_POT_RAMDOM;
	public static BlockEntityType<OakDrawerBlockEntity> OAK_DRAWER;
	public static BlockEntityType<SpruceDrawerBlockEntity> SPRUCE_DRAWER;
	public static BlockEntityType<JungleDrawerBlockEntity> JUNGLE_DRAWER;
	public static BlockEntityType<DarkOakDrawerBlockEntity> DARK_OAK_DRAWER;
	public static BlockEntityType<CherryDrawerBlockEntity> CHERRY_DRAWER;
	public static BlockEntityType<BirchDrawerBlockEntity> BIRCH_DRAWER;
	public static BlockEntityType<BambooDrawerBlockEntity> BAMBOO_DRAWER;
	public static BlockEntityType<AcaciaDrawerBlockEntity> ACACIA_DRAWER;
	public static BlockEntityType<MangroveDrawerBlockEntity> MANGROVE_DRAWER;
	public static BlockEntityType<BambooClusterBlockEntity> BAMBOO_CLUSTER;
	public static BlockEntityType<AirfryerBlockEntity> AIRFRYER;
	public static BlockEntityType<WoodenKitchenDrawerBlockEntity> WOODEN_KITCHEN_DRAWER;
	public static BlockEntityType<WoodenOvenCooktopBlockEntity> WOODEN_OVEN_COOKTOP;
	public static BlockEntityType<WoodenKitchenSinkBlockEntity> WOODEN_KITCHEN_SINK;
	public static BlockEntityType<WoodenKitchenExhausthoodBlockEntity> WOODEN_KITCHEN_EXHAUSTHOOD;
	public static BlockEntityType<WoodenKitchenCabinetAboveBlockEntity> WOODEN_KITCHEN_CABINET_ABOVE;

	public static void load() {
		CABINET_OAK = register("cabinet_oak", VoxelizedFurnitureModBlocks.CABINET_OAK, CabinetOakBlockEntity::new);
		CABINET_BIRCH = register("cabinet_birch", VoxelizedFurnitureModBlocks.CABINET_BIRCH, CabinetBirchBlockEntity::new);
		CABINET_DARK_OAK = register("cabinet_dark_oak", VoxelizedFurnitureModBlocks.CABINET_DARK_OAK, CabinetDarkOakBlockEntity::new);
		CABINET_ACACIA = register("cabinet_acacia", VoxelizedFurnitureModBlocks.CABINET_ACACIA, CabinetAcaciaBlockEntity::new);
		CABINET_MANGROVE = register("cabinet_mangrove", VoxelizedFurnitureModBlocks.CABINET_MANGROVE, CabinetMangroveBlockEntity::new);
		CABINET_CHERRY = register("cabinet_cherry", VoxelizedFurnitureModBlocks.CABINET_CHERRY, CabinetCherryBlockEntity::new);
		CABINET_JUNGLE = register("cabinet_jungle", VoxelizedFurnitureModBlocks.CABINET_JUNGLE, CabinetJungleBlockEntity::new);
		CABINET_BAMBOO = register("cabinet_bamboo", VoxelizedFurnitureModBlocks.CABINET_BAMBOO, CabinetBambooBlockEntity::new);
		FRIDGE = register("fridge", VoxelizedFurnitureModBlocks.FRIDGE, FridgeBlockEntity::new);
		CABINET_SPRUCE = register("cabinet_spruce", VoxelizedFurnitureModBlocks.CABINET_SPRUCE, CabinetSpruceBlockEntity::new);
		SHOWER = register("shower", VoxelizedFurnitureModBlocks.SHOWER, ShowerBlockEntity::new);
		OAK_SHELF = register("oak_shelf", VoxelizedFurnitureModBlocks.OAK_SHELF, OakShelfBlockEntity::new);
		SPRUCE_SHELF = register("spruce_shelf", VoxelizedFurnitureModBlocks.SPRUCE_SHELF, SpruceShelfBlockEntity::new);
		MANGROVE_SHELF = register("mangrove_shelf", VoxelizedFurnitureModBlocks.MANGROVE_SHELF, MangroveShelfBlockEntity::new);
		JUNGLE_SHELF = register("jungle_shelf", VoxelizedFurnitureModBlocks.JUNGLE_SHELF, JungleShelfBlockEntity::new);
		DARK_OAK_SHELF = register("dark_oak_shelf", VoxelizedFurnitureModBlocks.DARK_OAK_SHELF, DarkOakShelfBlockEntity::new);
		CHERRY_SHELF = register("cherry_shelf", VoxelizedFurnitureModBlocks.CHERRY_SHELF, CherryShelfBlockEntity::new);
		BIRCH_SHELF = register("birch_shelf", VoxelizedFurnitureModBlocks.BIRCH_SHELF, BirchShelfBlockEntity::new);
		BAMBOO_SHELF = register("bamboo_shelf", VoxelizedFurnitureModBlocks.BAMBOO_SHELF, BambooShelfBlockEntity::new);
		ACACIA_SHELF = register("acacia_shelf", VoxelizedFurnitureModBlocks.ACACIA_SHELF, AcaciaShelfBlockEntity::new);
		OAK_CHAIR_1 = register("oak_chair_1", VoxelizedFurnitureModBlocks.OAK_CHAIR_1, OakChair1BlockEntity::new);
		SPRUCE_CHAIR_1 = register("spruce_chair_1", VoxelizedFurnitureModBlocks.SPRUCE_CHAIR_1, SpruceChair1BlockEntity::new);
		MANGROVE_CHAIR_1 = register("mangrove_chair_1", VoxelizedFurnitureModBlocks.MANGROVE_CHAIR_1, MangroveChair1BlockEntity::new);
		JUNGLE_CHAIR_1 = register("jungle_chair_1", VoxelizedFurnitureModBlocks.JUNGLE_CHAIR_1, JungleChair1BlockEntity::new);
		DARK_OAK_CHAIR_1 = register("dark_oak_chair_1", VoxelizedFurnitureModBlocks.DARK_OAK_CHAIR_1, DarkOakChair1BlockEntity::new);
		CHERRY_CHAIR_1 = register("cherry_chair_1", VoxelizedFurnitureModBlocks.CHERRY_CHAIR_1, CherryChair1BlockEntity::new);
		BIRCH_CHAIR_1 = register("birch_chair_1", VoxelizedFurnitureModBlocks.BIRCH_CHAIR_1, BirchChair1BlockEntity::new);
		BAMBOO_CHAIR_1 = register("bamboo_chair_1", VoxelizedFurnitureModBlocks.BAMBOO_CHAIR_1, BambooChair1BlockEntity::new);
		ACACIA_CHAIR_1 = register("acacia_chair_1", VoxelizedFurnitureModBlocks.ACACIA_CHAIR_1, AcaciaChair1BlockEntity::new);
		OAK_WARDROBE = register("oak_wardrobe", VoxelizedFurnitureModBlocks.OAK_WARDROBE, OakWardrobeBlockEntity::new);
		SPRUCE_WARDROBE = register("spruce_wardrobe", VoxelizedFurnitureModBlocks.SPRUCE_WARDROBE, SpruceWardrobeBlockEntity::new);
		MANGROVE_WARDROBE = register("mangrove_wardrobe", VoxelizedFurnitureModBlocks.MANGROVE_WARDROBE, MangroveWardrobeBlockEntity::new);
		JUNGLE_WARDROBE = register("jungle_wardrobe", VoxelizedFurnitureModBlocks.JUNGLE_WARDROBE, JungleWardrobeBlockEntity::new);
		DARK_OAK_WARDROBE = register("dark_oak_wardrobe", VoxelizedFurnitureModBlocks.DARK_OAK_WARDROBE, DarkOakWardrobeBlockEntity::new);
		CHERRY_WARDROBE = register("cherry_wardrobe", VoxelizedFurnitureModBlocks.CHERRY_WARDROBE, CherryWardrobeBlockEntity::new);
		BIRCH_WARDROBE = register("birch_wardrobe", VoxelizedFurnitureModBlocks.BIRCH_WARDROBE, BirchWardrobeBlockEntity::new);
		BAMBOO_WARDROBE = register("bamboo_wardrobe", VoxelizedFurnitureModBlocks.BAMBOO_WARDROBE, BambooWardrobeBlockEntity::new);
		ACACIA_WARDROBE = register("acacia_wardrobe", VoxelizedFurnitureModBlocks.ACACIA_WARDROBE, AcaciaWardrobeBlockEntity::new);
		KITCHEN_DRAWER = register("kitchen_drawer", VoxelizedFurnitureModBlocks.KITCHEN_DRAWER, KitchenDrawerBlockEntity::new);
		KITCHEN_DRAWER_1 = register("kitchen_drawer_1", VoxelizedFurnitureModBlocks.KITCHEN_DRAWER_1, KitchenDrawer1BlockEntity::new);
		KITCHEN_SINK = register("kitchen_sink", VoxelizedFurnitureModBlocks.KITCHEN_SINK, KitchenSinkBlockEntity::new);
		OVEN = register("oven", VoxelizedFurnitureModBlocks.OVEN, OvenBlockEntity::new);
		OVEN_VENT = register("oven_vent", VoxelizedFurnitureModBlocks.OVEN_VENT, OvenVentBlockEntity::new);
		KITCHEN_FRIDGE = register("kitchen_fridge", VoxelizedFurnitureModBlocks.KITCHEN_FRIDGE, KitchenFridgeBlockEntity::new);
		CHERRY_DOORBELL = register("cherry_doorbell", VoxelizedFurnitureModBlocks.CHERRY_DOORBELL, CherryDoorbellBlockEntity::new);
		BIRCH_DOORBELL = register("birch_doorbell", VoxelizedFurnitureModBlocks.BIRCH_DOORBELL, BirchDoorbellBlockEntity::new);
		BAMBOO_DOORBELL = register("bamboo_doorbell", VoxelizedFurnitureModBlocks.BAMBOO_DOORBELL, BambooDoorbellBlockEntity::new);
		ACACIA_DOORBELL = register("acacia_doorbell", VoxelizedFurnitureModBlocks.ACACIA_DOORBELL, AcaciaDoorbellBlockEntity::new);
		MANGROVE_PORCH_TABLE = register("mangrove_porch_table", VoxelizedFurnitureModBlocks.MANGROVE_PORCH_TABLE, MangrovePorchTableBlockEntity::new);
		JUNGLE_PORCH_TABLE = register("jungle_porch_table", VoxelizedFurnitureModBlocks.JUNGLE_PORCH_TABLE, JunglePorchTableBlockEntity::new);
		DARK_OAK_PORCH_TABLE = register("dark_oak_porch_table", VoxelizedFurnitureModBlocks.DARK_OAK_PORCH_TABLE, DarkOakPorchTableBlockEntity::new);
		CHERRY_PORCH_TABLE = register("cherry_porch_table", VoxelizedFurnitureModBlocks.CHERRY_PORCH_TABLE, CherryPorchTableBlockEntity::new);
		BIRCH_PORCH_TABLE = register("birch_porch_table", VoxelizedFurnitureModBlocks.BIRCH_PORCH_TABLE, BirchPorchTableBlockEntity::new);
		BAMBOO_PORCH_TABLE = register("bamboo_porch_table", VoxelizedFurnitureModBlocks.BAMBOO_PORCH_TABLE, BambooPorchTableBlockEntity::new);
		ACACIA_PORCH_TABLE = register("acacia_porch_table", VoxelizedFurnitureModBlocks.ACACIA_PORCH_TABLE, AcaciaPorchTableBlockEntity::new);
		SPRUCE_TOILET_ROLL = register("spruce_toilet_roll", VoxelizedFurnitureModBlocks.SPRUCE_TOILET_ROLL, SpruceToiletRollBlockEntity::new);
		MANGROVE_TOILET_ROLL = register("mangrove_toilet_roll", VoxelizedFurnitureModBlocks.MANGROVE_TOILET_ROLL, MangroveToiletRollBlockEntity::new);
		JUNGLE_TOILET_ROLL = register("jungle_toilet_roll", VoxelizedFurnitureModBlocks.JUNGLE_TOILET_ROLL, JungleToiletRollBlockEntity::new);
		DARK_OAK_TOILET_ROLL = register("dark_oak_toilet_roll", VoxelizedFurnitureModBlocks.DARK_OAK_TOILET_ROLL, DarkOakToiletRollBlockEntity::new);
		CHERRY_TOILET_ROLL = register("cherry_toilet_roll", VoxelizedFurnitureModBlocks.CHERRY_TOILET_ROLL, CherryToiletRollBlockEntity::new);
		BIRCH_TOILET_ROLL = register("birch_toilet_roll", VoxelizedFurnitureModBlocks.BIRCH_TOILET_ROLL, BirchToiletRollBlockEntity::new);
		BAMBOO_TOILET_ROLL = register("bamboo_toilet_roll", VoxelizedFurnitureModBlocks.BAMBOO_TOILET_ROLL, BambooToiletRollBlockEntity::new);
		ACACIA_TOILET_ROLL = register("acacia_toilet_roll", VoxelizedFurnitureModBlocks.ACACIA_TOILET_ROLL, AcaciaToiletRollBlockEntity::new);
		SEED_IN_POT = register("seed_in_pot", VoxelizedFurnitureModBlocks.SEED_IN_POT, SeedInPotBlockEntity::new);
		SEED_IN_POT_RAMDOM = register("seed_in_pot_ramdom", VoxelizedFurnitureModBlocks.SEED_IN_POT_RAMDOM, SeedInPotRamdomBlockEntity::new);
		OAK_DRAWER = register("oak_drawer", VoxelizedFurnitureModBlocks.OAK_DRAWER, OakDrawerBlockEntity::new);
		SPRUCE_DRAWER = register("spruce_drawer", VoxelizedFurnitureModBlocks.SPRUCE_DRAWER, SpruceDrawerBlockEntity::new);
		JUNGLE_DRAWER = register("jungle_drawer", VoxelizedFurnitureModBlocks.JUNGLE_DRAWER, JungleDrawerBlockEntity::new);
		DARK_OAK_DRAWER = register("dark_oak_drawer", VoxelizedFurnitureModBlocks.DARK_OAK_DRAWER, DarkOakDrawerBlockEntity::new);
		CHERRY_DRAWER = register("cherry_drawer", VoxelizedFurnitureModBlocks.CHERRY_DRAWER, CherryDrawerBlockEntity::new);
		BIRCH_DRAWER = register("birch_drawer", VoxelizedFurnitureModBlocks.BIRCH_DRAWER, BirchDrawerBlockEntity::new);
		BAMBOO_DRAWER = register("bamboo_drawer", VoxelizedFurnitureModBlocks.BAMBOO_DRAWER, BambooDrawerBlockEntity::new);
		ACACIA_DRAWER = register("acacia_drawer", VoxelizedFurnitureModBlocks.ACACIA_DRAWER, AcaciaDrawerBlockEntity::new);
		MANGROVE_DRAWER = register("mangrove_drawer", VoxelizedFurnitureModBlocks.MANGROVE_DRAWER, MangroveDrawerBlockEntity::new);
		BAMBOO_CLUSTER = register("bamboo_cluster", VoxelizedFurnitureModBlocks.BAMBOO_CLUSTER, BambooClusterBlockEntity::new);
		AIRFRYER = register("airfryer", VoxelizedFurnitureModBlocks.AIRFRYER, AirfryerBlockEntity::new);
		WOODEN_KITCHEN_DRAWER = register("wooden_kitchen_drawer", VoxelizedFurnitureModBlocks.WOODEN_KITCHEN_DRAWER, WoodenKitchenDrawerBlockEntity::new);
		WOODEN_OVEN_COOKTOP = register("wooden_oven_cooktop", VoxelizedFurnitureModBlocks.WOODEN_OVEN_COOKTOP, WoodenOvenCooktopBlockEntity::new);
		WOODEN_KITCHEN_SINK = register("wooden_kitchen_sink", VoxelizedFurnitureModBlocks.WOODEN_KITCHEN_SINK, WoodenKitchenSinkBlockEntity::new);
		WOODEN_KITCHEN_EXHAUSTHOOD = register("wooden_kitchen_exhausthood", VoxelizedFurnitureModBlocks.WOODEN_KITCHEN_EXHAUSTHOOD, WoodenKitchenExhausthoodBlockEntity::new);
		WOODEN_KITCHEN_CABINET_ABOVE = register("wooden_kitchen_cabinet_above", VoxelizedFurnitureModBlocks.WOODEN_KITCHEN_CABINET_ABOVE, WoodenKitchenCabinetAboveBlockEntity::new);
	}

	// Start of user code block custom block entities
	// End of user code block custom block entities
	private static <T extends BlockEntity> BlockEntityType<T> register(String registryname, Block block, FabricBlockEntityTypeBuilder.Factory<? extends T> supplier) {
		return Registry.register(BuiltInRegistries.BLOCK_ENTITY_TYPE, Identifier.fromNamespaceAndPath(VoxelizedFurnitureMod.MODID, registryname), FabricBlockEntityTypeBuilder.<T>create(supplier, block).build());
	}
}